services:
  postgresql:
    image: postgres:17.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data